groups:
    - groupa
recipes:
attributes:
    homebrewalt:
        apps:
            - git-extras
        cask_apps:
            - adium
            - alfred
            - caffeine
            - ccmenu
            - dash
            - dropbox
            - evernote
            - heroku-toolbelt
            - hipchat
            - lastpass-universal
            - libreoffice
            - macvim
            - menumeters
            - minecraft
            - screenflow
            - scrivener
            - sequel-pro
            - skype
            - spotify
            - sublime-text
            - transmit
            - utorrent
            - vlc
            - vmware-fusion
            - vyprvpn
            - wireshark
            - xquartz
            - xscope
            - yubikey-personalization-gui
